# Build Stage
FROM node:22-alpine as build

WORKDIR /app

COPY package*.json ./
# Fix for potential Tailwind/PostCSS issues in docker
RUN npm install

COPY . .
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Custom Nginx config to handle React Router and API Proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
